### ISSUE TITLE
Frequent Crashes during reading(Beta r6789)

### ISSUE THREAD

**Issue by sounddrill31** [mihonapp/mihon#1096]
### Steps to reproduce

Nothing special, just normal use

Behavior is observed during reading through pages

### Expected behavior

Shouldn't crash and things should load

Beta version though, so it's understandable 

### Actual behavior

App occasionally crashes during reading

### Crash logs

![mihon_crash_logs.txt](https://github.com/user-attachments/files/16548675/mihon_crash_logs.txt)

### Mihon version

App version: 0.16.5-6789 (standard, 0af90999c, 7, 2024-07-27T21:18:15Z) Android version: 14 (SDK 34; build U1UGS34.23-82-2-2) Device brand: motorola Device manufacturer: motorola Device name: fogos (fogos_g) Device model: moto g34 5G WebView: Android System WebView 127.0.6533.64

### Android version

Android 14, stock rom with no OS modifications

### Device

Moto G34 5g (Fogos)

### Other details

Battery saver is enabled, along with device's "App Battery Usage" feature set to Restrict"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by sounddrill31** [comment]
Not sure if it is extension related but if it helps, I was using a MangaDex extension at the time of taking these crash logs

**Comment by MajorTanya** [comment]
> Not sure if it is extension related but if it helps, I was using a MangaDex extension at the time of taking these crash logs
> 
> Updated to r6793, will come back with crash logs if it happens again

Please avoid naming extensions both here and on the Discord server since Mihon is not associated with or providing support for extensions,

**Comment by sounddrill31** [comment]
> > Not sure if it is extension related but if it helps, I was using a MangaDex extension at the time of taking these crash logs
> > 
> > Updated to r6793, will come back with crash logs if it happens again
> 
> Please avoid naming extensions both here and on the Discord server since Mihon is not associated with or providing support for extensions.

My mistake

I have updated my comment, thanks for letting me know. 

Thanks a lot for continuing this project, it means a lot to me and the rest of the community and none of us want it to face trouble again.

**Comment by sounddrill31** [comment]
Similar crash:

![mihon_crash_logs.txt](https://github.com/user-attachments/files/16552434/mihon_crash_logs.txt)

Happened in the same way(while reading)

App version: 0.16.5-6793 (standard, de8ef6dad, 7, 2024-08-03T21:19:24Z)
Android version: 14 (SDK 34; build U1UGS34.23-82-2-2)
Device brand: motorola
Device manufacturer: motorola
Device name: fogos (fogos_g)
Device model: moto g34 5G
WebView: Android System WebView 127.0.6533.64

**Comment by FooIbar** [comment]
Decoded stack trace:
```
java.lang.Throwable: java.lang.IndexOutOfBoundsException: Index: 41, Size: 40
        at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:763)
        at java.util.ArrayList.add(ArrayList.java:488)
        at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewerAdapter.setChapters(PagerViewerAdapter.kt:84)
        at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.setChaptersInternal(PagerViewer.kt:280)
        at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerViewer.setChapters(PagerViewer.kt:268)
        at eu.kanade.tachiyomi.ui.reader.ReaderActivity.setChapters(ReaderActivity.kt:599)
        at eu.kanade.tachiyomi.ui.reader.ReaderActivity.access$setChapters(ReaderActivity.kt:103)
        at eu.kanade.tachiyomi.ui.reader.ReaderActivity$onCreate$9.invokeSuspend(ReaderActivity.kt:215)
```
Corresponding source:
https://github.com/mihonapp/mihon/blob/3f050a83dd0907e0ffb56a1e1833f9de5b10b329/app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt#L78-L85

You can disable "split wide pages" as a workaround before it gets fixed.
