### ISSUE TITLE
Downloaded Chapter Folder Name Affects Download Index

### ISSUE THREAD

**Issue by TheKingTermux** [mihonapp/mihon#1455]
### Steps to reproduce

1. Download chapter from previous Tachiyomi or Mihon
2. Download Latest Mihon
3. Re-Index Liblary
4. Problem Found

### Expected behavior

The downloaded Chapter can be read

### Actual behavior

Downloaded Chapter Can't be read because in the download folder name have (_) on the first name, because of that many Chapter Can't be Index during Starting Mihon from the beginning, but the downloaded chapter counter (in the library) shows the total available chapters and the total downloaded chapters are the same

Example :
My last download Chapter in Mihon is (Chapter xxx), from my previous Tachiyomi or Mihon is (_Chapter xxx), the detailed Action is on _Other Details_ column

### Crash logs

App version: 0.17.0 (standard, 38d5fc9, 8, 2024-10-26T17:39:14Z)
Android version: 11 (SDK 30; build RMX2103_11_C.17)
Device brand: realme
Device manufacturer: realme
Device name: RE50C1 (RMX2103T2)
Device model: RMX2103
WebView: Android System WebView 131.0.6778.22

--------- beginning of system
--------- beginning of main
11-08 15:48:41.356 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:48:53.177 18874 23307 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:48:54.251 18874 18874 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:48:54.367 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:49:19.948 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:49:28.928 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:49:41.397 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:49:54.528 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:50:07.028 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:50:18.982 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:50:36.945 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:50:47.460 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:50:53.773 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:51:17.995 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:51:24.364 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:51:34.617 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:51:46.041 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:51:57.592 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:52:16.286 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:52:22.184 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:52:41.549 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:55:16.649 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:55:31.499 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:55:45.203 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:55:54.733 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:56:04.244 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:56:11.339 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 15:58:53.726 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 16:13:56.616 18874 29460 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 16:13:58.237 18874 29467 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 16:20:19.084 18874 22425 E libEGL  : Invalid file path for libcolorx-loader.so
11-08 16:27:20.915 18874 22069 E DatabaseUtils: Writing exception to parcel
11-08 16:27:20.915 18874 22069 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://app.mihon.provider/ext_cache_files/mihon_crash_logs.txt from pid=15788, uid=1000 requires the provider be exported, or grantUriPermission()
11-08 16:27:20.915 18874 22069 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
11-08 16:27:20.915 18874 22069 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
11-08 16:27:20.915 18874 22069 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
11-08 16:27:20.915 18874 22069 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
11-08 16:27:20.915 18874 22069 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1161)
11-08 16:27:20.915 18874 22069 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1130)
11-08 16:29:03.218 18874 22189 E DatabaseUtils: Writing exception to parcel
11-08 16:29:03.218 18874 22189 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://app.mihon.provider/ext_cache_files/mihon_crash_logs.txt from pid=18340, uid=1000 requires the provider be exported, or grantUriPermission()
11-08 16:29:03.218 18874 22189 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
11-08 16:29:03.218 18874 22189 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
11-08 16:29:03.218 18874 22189 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
11-08 16:29:03.218 18874 22189 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
11-08 16:29:03.218 18874 22189 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1161)
11-08 16:29:03.218 18874 22189 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1130)
11-08 16:29:31.357 18874 22181 E DatabaseUtils: Writing exception to parcel
11-08 16:29:31.357 18874 22181 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://app.mihon.provider/ext_cache_files/mihon_crash_logs.txt from pid=18340, uid=1000 requires the provider be exported, or grantUriPermission()
11-08 16:29:31.357 18874 22181 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
11-08 16:29:31.357 18874 22181 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
11-08 16:29:31.357 18874 22181 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
11-08 16:29:31.357 18874 22181 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
11-08 16:29:31.357 18874 22181 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1161)
11-08 16:29:31.357 18874 22181 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1130)

### Mihon version

0.17.0

### Android version

Android 11

### Device

Realme 7i

### Other details

List of proof 

1. Example of the Manga from the Liblary
![Screenshot_2024-11-08-20-47-56-99_551f7f0ca926862b368845ce7ee433aa.jpg](https://github.com/user-attachments/assets/4f71911f-6765-4916-afef-665097e220f2) 
![Screenshot_2024-11-08-16-18-24-56_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/d7b00f3a-e478-4716-9152-a7c8709f2685)
![Screenshot_2024-11-08-16-19-00-38_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/261d5fe4-b9fd-4f46-a74a-61098ac409e0)

2. Example of the Downloaded that Manga
![Screenshot_2024-11-08-16-18-51-90_83ab3b20d3fba5c9c905d050db1f8de3](https://github.com/user-attachments/assets/42ffb176-1904-4929-aeef-2a743335f53b)
![Screenshot_2024-11-08-16-36-13-57_83ab3b20d3fba5c9c905d050db1f8de3](https://github.com/user-attachments/assets/07cfeced-e6e9-4ae4-a4b1-a258db41d381)

3. Renaming Folder from (_Chapter xxx) to (Chapter xxx)
![IMG_20241108_174653](https://github.com/user-attachments/assets/9bc1e486-d9e2-47d8-9562-a90f5b7753f9)

4. Re-Indexing Liblary 
![Screenshot_2024-11-08-16-20-14-14_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/bad1e41f-f5c3-4067-a44a-9e30130545e6)

5. Problem Solved after Renaming Folder 
![Screenshot_2024-11-08-16-21-22-45_551f7f0ca926862b368845ce7ee433aa](https://github.com/user-attachments/assets/8fce8cdf-96e9-4c62-871f-ad3b6cea6895)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
The other naming format had been deprecated since 2023 at maximum and also given there haven't been much uproar I'm not gonna reintroduce it again
