### ISSUE TITLE
Failed to download 

### ISSUE THREAD

**Issue by revonateB0T** [mihonapp/mihon#1566]
### Steps to reproduce

download manga

### Expected behavior

Works as intended.

### Actual behavior

![Screenshot_20241212_114920_me zhanghai android files](https://github.com/user-attachments/assets/dbeb4d51-d4bd-4c7d-b55e-704b25cc77b4)
Where all directory are empty.

### Crash logs

```
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: Failed to createFile
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/emulated/0/Download/mihon/downloads (5)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2086)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2046)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2080)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1327)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at coil.util.-Collections.createFile(Unknown Source:4)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(Unknown Source:28)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at tachiyomi.domain.storage.service.StorageManager.getDownloadsDirectory(Unknown Source:6)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.findSourceDir(Unknown Source:7)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.source.AndroidSourceManager$registerStubSource$1.invokeSuspend(Unknown Source:107)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
12-12 11:41:23.492 21388 21453 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:57)
```

### Mihon version

0.17.1

### Android version

Android 10

### Device

SCM-W09

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Come to the Mihon Discord support channel for help, since you decided to put Mihon's storage location into your device's System folders.
