### ISSUE TITLE
Downloaded chapter arent saved to storage

### ISSUE THREAD

**Issue by smarttommyau** [mihonapp/mihon#1569]
### Steps to reproduce

Just download a chapter

### Expected behavior

After all page is downloaded, it should be saved.

### Actual behavior

Instead, after all page downloaded, it failed to saved and shows error.

### Crash logs

App version: 0.17.1 (standard, 3a100c7, 9, 2024-12-06T17:14:05Z)
Android version: 12 (SDK 31; build System 104.5.0.001(00FV))
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWHBP (HBP-AL00)
Device model: HBP-AL00
WebView: Huawei WebView 14.0.2.316

--------- beginning of main
12-12 19:35:50.236 62897 62912 E BLASTBufferQueue: [app.mihon/eu.kanade.tachiyomi.ui.main.MainActivity#10](f:0,a:3) ERROR: releaseBufferCallback without corresponding submitted buffer bufferId:270140558016591 framenumber:1034
12-12 19:35:50.286 62897 62912 E BLASTBufferQueue: [app.mihon/eu.kanade.tachiyomi.ui.main.MainActivity#10](f:0,a:3) ERROR: releaseBufferCallback without corresponding submitted buffer bufferId:270140558016586 framenumber:1036
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: Failed to renameTo
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to rename to /storage/emulated/0/mihon/downloads/拷贝漫画 (ZH)/同班同學是重返青春的前妻/第05話_tmp/002.webp
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2451)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2427)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2410)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2554)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1446)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.renameTo(Unknown Source:11)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadImage$2.invokeSuspend(Unknown Source:118)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
12-12 19:35:50.398 62897 63311 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:57)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: Failed to renameTo
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to rename to /storage/emulated/0/mihon/downloads/动漫之家 (ZH)/恋上朋友姐姐的男孩子/連載05.1_tmp/005.jpg
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2451)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2427)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2410)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2554)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1446)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.renameTo(Unknown Source:11)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadImage$2.invokeSuspend(Unknown Source:118)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
12-12 19:35:51.308 62897 63650 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:57)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: Failed to renameTo
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to rename to /storage/emulated/0/mihon/downloads/拷贝漫画 (ZH)/同班同學是重返青春的前妻/第05話_tmp/005.webp
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2451)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2427)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2410)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2554)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1446)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.renameTo(Unknown Source:11)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadImage$2.invokeSuspend(Unknown Source:118)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
12-12 19:35:51.331 62897 63318 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:57)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: Failed to renameTo
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to rename to /storage/emulated/0/mihon/downloads/动漫之家 (ZH)/恋上朋友姐姐的男孩子/連載05.1_tmp/006.jpg
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2451)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2427)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2410)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2554)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1446)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.renameTo(Unknown Source:11)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadImage$2.invokeSuspend(Unknown Source:118)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
12-12 19:35:51.379 62897 63303 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:57)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: Failed to renameTo
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to rename to /storage/emulated/0/mihon/downloads/拷贝漫画 (ZH)/同班同學是重返青春的前妻/第05話_tmp/006.webp
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2451)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2427)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2410)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2554)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1446)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.renameTo(Unknown Source:11)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadImage$2.invokeSuspend(Unknown Source:118)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
12-12 19:35:51.447 62897 63664 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:57)
12-12 19:35:52.008 62897 63827 E DMZJ    : failed to fetch 'https://images.idmzj.com/l%2F%E6%81%8B%E4%B8%8A%E6%9C%8B%E5%8F%8B%E5%A7%90%E5%A7%90%E7%9A%84%E7%94%B7%E5%AD%A9%E5%AD%90%2F%E9%80%A3%E8%BC%8905.1_1733856932%2F1-96.jpg'
12-12 19:35:52.008 62897 63827 E DMZJ    : java.io.IOException: Canceled
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(Unknown Source:210)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.extension.zh.dmzj.CommentsInterceptor.intercept(CommentsInterceptor.kt:26)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.extension.zh.dmzj.ImageUrlInterceptor.intercept(ImageUrlInterceptor.kt:17)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(SourceFile:2)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(Unknown Source:27)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.network.interceptor.UncaughtExceptionInterceptor.intercept(Unknown Source:9)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(Unknown Source:99)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:43)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-12 19:35:52.008 62897 63827 E DMZJ    : 	at java.lang.Thread.run(Thread.java:933)
12-12 19:35:52.009 62897 63827 E DMZJ    : failed to fetch 'https://images.idmzj.com/l/恋上朋友姐姐的男孩子/連載05.1_1733856932/1-96.jpg'
12-12 19:35:52.009 62897 63827 E DMZJ    : java.io.IOException: Canceled
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(Unknown Source:210)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.extension.zh.dmzj.CommentsInterceptor.intercept(CommentsInterceptor.kt:26)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.extension.zh.dmzj.ImageUrlInterceptor.intercept(ImageUrlInterceptor.kt:29)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(SourceFile:2)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(Unknown Source:27)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at eu.kanade.tachiyomi.network.interceptor.UncaughtExceptionInterceptor.intercept(Unknown Source:9)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:142)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(Unknown Source:99)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:43)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-12 19:35:52.009 62897 63827 E DMZJ    : 	at java.lang.Thread.run(Thread.java:933)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: Failed to renameTo
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to rename to /storage/emulated/0/mihon/downloads/拷贝漫画 (ZH)/同班同學是重返青春的前妻/第05話_tmp/008.webp
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2451)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:2427)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:2410)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2554)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1446)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.renameTo(Unknown Source:11)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$downloadImage$2.invokeSuspend(Unknown Source:118)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
12-12 19:35:52.098 62897 63318 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:57)
--------- beginning of system
12-12 19:35:53.844 62897 62897 E LOGLIMIT: process app.mihon drop 22 lines, from time:1734003348 to time:1734003353, threshold:13050

### Mihon version

0.17.1

### Android version

Android 12(DroiTong container under HarmonyOS Next)

### Device

HUAWEI Pura 70 ultra

### Other details

This container is very new, therefore it is uncertain if this it due to some issues in the container or is something can be done on the mihon side.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
1. You can just upload the crash log file instead of pasting the whole chunk of text here.
2. I'm inclined to say it's because you're trying to run the app in whatever container/unsupported setup.

From a Reddit post talking about this container thing:
![Screenshot_20241212_205425_RVX Reddit.png](https://github.com/user-attachments/assets/6fb0cf20-be20-421b-b83a-153565ae7762)

**Comment by smarttommyau** [comment]
> 1. You can just upload the crash log file instead of pasting the whole chunk of text here.
> 2. I'm inclined to say it's because you're trying to run the app in whatever container/unsupported setup.
> 
> From a Reddit post talking about this container thing (mainly about the file access bit):
> 
> ![Screenshot_20241212_205425_RVX Reddit.png](https://private-user-images.githubusercontent.com/155411819/395169003-6fb0cf20-be20-421b-b83a-153565ae7762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMjcxMzksIm5iZiI6MTczNDAyNjgzOSwicGF0aCI6Ii8xNTU0MTE4MTkvMzk1MTY5MDAzLTZmYjBjZjIwLWJlMjAtNDIxYi1iODNhLTE1MzU2NWFlNzc2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQxODA3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjFjZjc3ZmNmY2UyYWNhYmE0NGE1NzQ1NjI3NjZlZTI3Y2MyZGY2MzY1MmZhNTY2MzhjZGU0ODJiNjhmMGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ADEdTdRHI9wksdsEFQRkZ6mTU9-n7lumAI5jmoOmOM0)

1. I am sorry for the chunk. Edited with a txt file.
2. For reddit post you mention, it has no relationship for what he mentioned. He mention about the filesystem access between the host system and the container. But, mihon is running in container and saving in container, not writing to the host system, so it is not the case.

I just take a look on the code that cause the error, the issue is kind of weird. While using a similar api for creating file and renaming files in the code, which call the same api from Android, only renaming files crash the code. Probably is some issue with incomplete support to DocumentsProvider. Anyway, I have also contact the team of Droitong, see if they can follow up the issue.

**Comment by molamooo** [comment]
Same issue on Mate X5 with DroiTong container under HarmonyOS Next. Is there any workaround?

**Comment by smarttommyau** [comment]
> Same issue on Mate X5 with DroiTong container under HarmonyOS Next. Is there any workaround?

Only work around now, is to rename chapter folder with  '_tmp' to without '_tmp', images with '.tmp' to something like '.jpg'  with a file explorer manually. Then, mihon can identify the downloaded chapters

**Comment by diannaojiang** [comment]
I also encountered this issue, and I came to the same conclusion as you. I believe that if the pull request [5266](https://github.com/mihonapp/mihon/pull/1738) is accepted, it may solve the problem, but the author seems unwilling to merge it.

**Comment by AntsyLich** [comment]
@diannaojiang your comment is as close to the issue as Point Nemo is to the nearest land mass
