### ISSUE TITLE
Downloading failed

### ISSUE THREAD

**Issue by thaddy18** [mihonapp/mihon#1584]
### Steps to reproduce

I don't know what to input here, but my issues was I can't download the episode I wanted to download. It says "failed to connect…" 
![Screenshot_2024_1217_231446](https://github.com/user-attachments/assets/5b73cdd6-467b-49a6-8045-07fa9a76b252)

### Expected behavior

I want you to fix it.

### Actual behavior

I don't know what is happening; my signal were fine.

### Crash logs

App version: 0.17.1-7033 (standard, 69320e4d0, 9, 2024-12-14T21:20:50Z)
Android version: 11 (SDK 30; build RP1A.200720.012 release-keys)
Device brand: vivo
Device manufacturer: vivo
Device name: 1901 (1901)
Device model: vivo 1901
WebView: Android System WebView 131.0.6778.135

--------- beginning of main
12-17 22:51:14.322  7055  7055 E app.mihon.debu: Not starting debugger since process cannot load the jdwp agent.
12-17 22:51:15.072  7055  7089 E SQLiteLog: (283) recovered 3 frames from WAL file /data/data/app.mihon.debug/databases/tachiyomi.db-wal
12-17 22:51:15.103  7055  7123 E app.mihon.debu: No package ID 76 found for ID 0x760b000f.
12-17 22:51:15.104  7055  7123 E app.mihon.debu: No package ID 76 found for ID 0x760b000f.
12-17 22:51:16.218  7055  7146 E chromium: [1217/225116.213544:ERROR:variations_seed_loader.cc(39)] Seed missing signature.
12-17 22:51:16.982  7055  7169 E SQLiteLog: (284) automatic index on C(manga_id)
12-17 22:51:16.982  7055  7169 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-17 22:51:18.025  7055  7191 E ion     : ioctl c0044901 failed with code -1: Invalid argument
12-17 22:51:18.034  7055  7191 E ion     : ioctl c0044901 failed with code -1: Invalid argument
12-17 22:51:56.131  7687  7687 E app.mihon.debu: Not starting debugger since process cannot load the jdwp agent.
12-17 22:51:57.192  7687  7796 E app.mihon.debu: No package ID 76 found for ID 0x760b000f.
12-17 22:51:57.196  7687  7796 E app.mihon.debu: No package ID 76 found for ID 0x760b000f.
12-17 22:51:59.660  7687  7941 E SQLiteLog: (284) automatic index on C(manga_id)
12-17 22:51:59.660  7687  7941 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-17 22:52:00.358  7687  7892 E ion     : ioctl c0044901 failed with code -1: Invalid argument
12-17 22:52:00.400  7687  7892 E ion     : ioctl c0044901 failed with code -1: Invalid argument
12-17 22:59:10.787 14715 14715 E app.mihon.debu: Not starting debugger since process cannot load the jdwp agent.
12-17 22:59:13.198 14715 14917 E app.mihon.debu: No package ID 76 found for ID 0x760b000f.
12-17 22:59:13.199 14715 14917 E app.mihon.debu: No package ID 76 found for ID 0x760b000f.
12-17 22:59:17.017 14715 15226 E SQLiteLog: (284) automatic index on C(manga_id)
12-17 22:59:17.017 14715 15226 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-17 22:59:17.918 14715 15234 E ion     : ioctl c0044901 failed with code -1: Invalid argument
12-17 22:59:17.971 14715 15234 E ion     : ioctl c0044901 failed with code -1: Invalid argument
12-17 23:00:15.782 14715 14715 E libc    : Access denied finding property "ro.vendor.scroll.preobtain.enable"
12-17 23:06:29.832 20718 20718 E app.mihon.debu: Not starting debugger since process cannot load the jdwp agent.
12-17 23:06:30.666 20718 20783 E app.mihon.debu: No package ID 76 found for ID 0x760b000f.
12-17 23:06:30.668 20718 20783 E app.mihon.debu: No package ID 76 found for ID 0x760b000f.
12-17 23:06:33.193 20718 20756 E SQLiteLog: (284) automatic index on C(manga_id)
12-17 23:06:33.193 20718 20756 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-17 23:06:33.897 20718 20854 E ion     : ioctl c0044901 failed with code -1: Invalid argument
12-17 23:06:33.909 20718 20854 E ion     : ioctl c0044901 failed with code -1: Invalid argument
12-17 23:07:12.312 20718 20832 E Downloader: java.net.SocketTimeoutException: failed to connect to pic1.mangapicgallery.com/104.23.132.69 (port 443) from /192.168.1.4 (port 42742) after 30000ms
12-17 23:07:12.312 20718 20832 E Downloader: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:190)
12-17 23:07:12.312 20718 20832 E Downloader: 	at libcore.io.IoBridge.connect(IoBridge.java:134)
12-17 23:07:12.312 20718 20832 E Downloader: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
12-17 23:07:12.312 20718 20832 E Downloader: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
12-17 23:07:12.312 20718 20832 E Downloader: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
12-17 23:07:12.312 20718 20832 E Downloader: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
12-17 23:07:12.312 20718 20832 E Downloader: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
12-17 23:07:12.312 20718 20832 E Downloader: 	at java.net.Socket.connect(Socket.java:621)
12-17 23:07:12.312 20718 20832 E Downloader: 	at okhttp3.internal.platform.Platform.connectSocket(Unknown Source:10)
12-17 23:07:12.312 20718 20832 E Downloader: 	at okhttp3.internal.connection.ConnectPlan.connectSocket(Unknown Source:73)
12-17 23:07:12.312 20718 20832 E Downloader: 	at okhttp3.internal.connection.ConnectPlan.connectTcp(Unknown Source:15)
12-17 23:07:12.312 20718 20832 E Downloader: 	at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(Unknown Source:2)
12-17 23:07:12.312 20718 20832 E Downloader: 	at okhttp3.internal.concurrent.TaskRunner.access$runTask(Unknown Source:15)
12-17 23:07:12.312 20718 20832 E Downloader: 	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(Unknown Source:48)
12-17 23:07:12.312 20718 20832 E Downloader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-17 23:07:12.312 20718 20832 E Downloader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-17 23:07:12.312 20718 20832 E Downloader: 	at java.lang.Thread.run(Thread.java:923)
12-17 23:07:12.312 20718 20832 E Downloader: 	Suppressed: java.net.SocketTimeoutException: failed to connect to pic1.mangapicgallery.com/104.23.131.69 (port 443) from /192.168.1.4 (port 34160) after 30000ms
12-17 23:07:12.312 20718 20832 E Downloader: 		... 17 more
12-17 23:07:12.312 20718 20832 E Downloader: Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(Unknown Source:19)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(Unknown Source:12)
12-17 23:07:12.312 20718 20832 E Downloader: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(Unknown Source:31)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.Subscriber.setProducer(Unknown Source:38)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(Unknown Source:2)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.Subscriber.setProducer(Unknown Source:21)
12-17 23:07:12.312 20718 20832 E Downloader: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda0.call(Unknown Source:20)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.Observable.unsafeSubscribe(Unknown Source:9)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.internal.operators.OnSubscribeDoOnEach.call(SourceFile:2)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.internal.operators.OnSubscribeDoOnEach.call(SourceFile:1)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.Observable.unsafeSubscribe(Unknown Source:9)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.internal.operators.OnSubscribeMap.call(SourceFile:5)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.internal.operators.OnSubscribeMap.call(SourceFile:1)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.internal.operators.OnSubscribeLift.call(SourceFile:4)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.internal.operators.OnSubscribeLift.call(SourceFile:1)
12-17 23:07:12.312 20718 20832 E Downloader: 	at rx.Observable.subscribe(SourceFile:24)
12-17 23:07:12.312 20718 20832 E Downloader: 	at tachiyomi.core.common.util.lang.RxCoroutineBridgeKt.awaitSingle(Unknown Source:22)
12-17 23:07:12.312 20718 20832 E Downloader: 	at eu.kanade.tachiyomi.source.online.HttpSource.getPageList(Unknown Source:4)
12-17 23:07:12.312 20718 20832 E Downloader: 	at eu.kanade.tachiyomi.data.download.Downloader.access$downloadChapter(Unknown Source:302)
12-17 23:07:12.312 20718 20832 E Downloader: 	at eu.kanade.tachiyomi.data.download.Downloader$launchDownloadJob$1.invokeSuspend(Unknown Source:44)
12-17 23:07:12.312 20718 20832 E Downloader: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
12-17 23:07:12.312 20718 20832 E Downloader: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
12-17 23:07:12.312 20718 20832 E Downloader: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
12-17 23:07:12.312 20718 20832 E Downloader: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
12-17 23:07:12.312 20718 20832 E Downloader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
12-17 23:07:12.312 20718 20832 E Downloader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:57)
12-17 23:07:55.619 20718 20850 E Downloader: java.net.SocketTimeoutException: failed to connect to pic1.mangapicgallery.com/104.23.132.69 (port 443) from /192.168.1.4 (port 42756) after 30000ms
12-17 23:07:55.619 20718 20850 E Downloader: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:190)
12-17 23:07:55.619 20718 20850 E Downloader: 	at libcore.io.IoBridge.connect(IoBridge.java:134)
12-17 23:07:55.619 20718 20850 E Downloader: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
12-17 23:07:55.619 20718 20850 E Downloader: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
12-17 23:07:55.619 20718 20850 E Downloader: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
12-17 23:07:55.619 20718 20850 E Downloader: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
12-17 23:07:55.619 20718 20850 E Downloader: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
12-17 23:07:55.619 20718 20850 E Downloader: 	at java.net.Socket.connect(Socket.java:621)
12-17 23:07:55.619 20718 20850 E Downloader: 	at okhttp3.internal.platform.Platform.connectSocket(Unknown Source:10)
12-17 23:07:55.619 20718 20850 E Downloader: 	at okhttp3.internal.connection.ConnectPlan.connectSocket(Unknown Source:73)
12-17 23:07:55.619 20718 20850 E Downloader: 	at okhttp3.internal.connection.ConnectPlan.connectTcp(Unknown Source:15)
12-17 23:07:55.619 20718 20850 E Downloader: 	at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(Unknown Source:2)
12-17 23:07:55.619 20718 20850 E Downloader: 	at okhttp3.internal.concurrent.TaskRunner.access$runTask(Unknown Source:15)
12-17 23:07:55.619 20718 20850 E Downloader: 	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(Unknown Source:48)
12-17 23:07:55.619 20718 20850 E Downloader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-17 23:07:55.619 20718 20850 E Downloader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-17 23:07:55.619 20718 20850 E Downloader: 	at java.lang.Thread.run(Th

### Mihon version

0.17.1-7033

### Android version

Android 11

### Device

Device name: 1901 (1901) Device model: vivo 1901

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Not an app-related issue, we can't fix your personal network issues.

> ### Troubleshooting issues
> * Please check the Mihon website's [troubleshooting guide](<https://mihon.app/docs/guides/troubleshooting/>) for the issue you are experiencing:
> -# ** **
> ### Common issues:
> 1. [**Connection-related issues**](<https://mihon.app/docs/guides/troubleshooting/common-issues#advanced-errors>)
>     * For "Unable to resolve host", "connection reset", "timeout", "java.security.cert.CertPathValidatorException" issues
> 2. [**Cloudflare & user-agent issues**](<https://mihon.app/docs/guides/troubleshooting/#cloudflare>)
>     * For Cloudflare looping issues & how to change your user-agent
> 3. [**HTTP errors**](<https://mihon.app/docs/guides/troubleshooting/common-issues#http-errors>)
>     * For HTTP 404, 429, 502, 520, etc questions
> 4. **"Image could not be loaded" error in the Reader**
>     * Check WebView for issues
>     * Check with whoever/wherever you get your extensions from for any known issues, __do not ask here, rule 10__
