### ISSUE TITLE
CMYK JPEGs cannot be decoded

### ISSUE THREAD

**Issue by beerpiss** [mihonapp/mihon#243]
### Steps to reproduce

1. Open a page with CMYK JPEGs
2. See infinite loading wheel

### Expected behavior

The image should successfully load.

### Actual behavior

The image doesn't load, and an infinite loading wheel is shown instead.

### Mihon version

Mihon Preview r6458

### Android version

Android 14

### Device

Google Pixel 7

### Other details

Minimal local manga entry for reproduction: [CMYK JPEG example.zip](https://github.com/mihonapp/mihon/files/14071831/CMYK.JPEG.example.zip)

Possibly relevant logcat output:

```
2024-01-27 16:29:53.840 29705-1580  ImageDecoder            app.mihon.debug                      E  Unsupported color conversion request
2024-01-27 16:29:53.840 29705-1580  Subsamplin...eImageView app.mihon.debug                      E  Failed to decode tile
                                                                                                    java.lang.RuntimeException: Null region bitmap
                                                                                                    	at com.davemorrissey.labs.subscaleview.decoder.ImageDecoder.decodeRegion(Unknown Source:21)
                                                                                                    	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SourceFile:9)
                                                                                                    	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SourceFile:1)
                                                                                                    	at android.os.AsyncTask$3.call(AsyncTask.java:394)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment]
Should potentially be fixed by this upstream pr https://github.com/tachiyomiorg/image-decoder/pull/10
