### ISSUE TITLE
Intermittent crash while navigating between library and search

### ISSUE THREAD

**Issue by dgw** [mihonapp/mihon#436]
### Steps to reproduce

This is just what I had done during the most recent occurrence. It's not really a guaranteed reproducer due to the nature of this potential bug.

1. Leave Mihon open in the background for a while, on a series page
2. Return to library
3. Perform a global search
4. View a couple of the search results
5. Add one of the search results to library
6. Back out of the search

### Expected behavior

Eventually the main library view is displayed again

### Actual behavior

Mihon crashes with the error trace below

### Crash logs

_Note: I had to extract these from a screenshot using Google Lens, as the traceback display doesn't allow selecting text. Original screenshot included below._

java.lang.Throwable: java.lang.IllegalArgumentException: Key eu.kanade.tachiyomi.ui.library.LibraryTab:current Tab was used multiple times

at coll.compose UtilsKtSonStateOf$1 invoke(SourceFile:17) at coil.compose UtilsKtSonStateOf$1.invoke(SourceFile:165)

at androidx.compose.runtime. DisposableEffectimpl.onRemembered (Unknown Source:4)

at androidx.compose.runtime.CompositionimplŞRememberEventDispatcher.dispatch RememberObservers(Unknown Source: 103)

at androidx.compose.runtime.Compositionimpl.applyChangesInLocked(Unknown Source:63)

at androidx.compose.runtime.CompositionImpl.applyChanges (Unknown Source 5)

at androidx.compose.runtime. Recomposer Srun RecomposeAndApplyChanges$2$1 invoke(Unknown Source:201)

at androidx.compose ui platform. AndroidUiFrameClockSwithFrameNanos$2Scallback$1.doFrame(Unknown Source:6)

at androidx.compose.ul platform. AndroidUiDispatcherSdispatchCallback$1.doFrame(Unknown Source:47)

at android.view.Choreographer$Callback Record.run(Choreographer.java:1550) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1561)

at android.view.Choreographer.doCallbacks(Choreographer.java:1117)

at android.view Choreographer.doFrame(Choreographer.java:992)

at android view Choreographer FrameDisplay EventReceiver run(Choreographer java:1535)

at android.os.Handler.handleCallback(Handler.java:958)

at android.os.Handler.dispatchMessage(Handler.java:99)

at android.os.Looper.loopOnce(Looper.java: 257)

at android.os.Looper.loop(Looper.java:368)

at android.app.ActivityThread.main(ActivityThread.java:8825)

at java.lang.reflect.Method.invoke(Native Method) at com.android. intemal.os. RuntimelnitŚMethodAndArgsCaller.nun(Runtimelnit.java:572)

at com android internal.os.ZygoteInit.main(Zygotelnit.java:1049)

Suppressed: kotlinx coroutines.internal. DiagnosticCoroutineContextException: [androidx.compose.runtime. PausableMonotonicFrameClock@bacf967, androidx.compose.ui.platform.MotionDurationScalelmpl@94dc314, StandaloneCoroutine(Cancelling)@d0457bd, AndroidUIDispatcher@6c321b2|

![Screenshot_2024-02-20-23-32-57-76_551f7f0ca926862b368845ce7ee433aa](https://github.com/mihonapp/mihon/assets/164140/730bc574-61d1-475d-afd6-6573ed28fc45)

### Mihon version

0.16.3

### Android version

OxygenOS 14

### Device

OnePlus Pad

### Other details

I've had this crash on a pretty regular basis since switching from Tachiyomi by importing my library backup. I have searched the issue tracker a few separate times to see if the error type or Key was mentioned in any existing issues.

Finally, this time, I had a moment to sit down and actually report it, since it seems like no one else has yet.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment]
Very well known issue but we currently have no fix or workaround at hand for this. Thanks for filing the issue.

**Comment by AriaMoradi** [comment]
I face this crash at least a couple of times a day, I can reproduce it randomly by 
1- leaving the app in the background for a while on library page sceeen (I have multiple categories) 
2- edge swiping back to close the app
This usually happens when the swiping gesture also swipes the category tabs at the same time.

The device is Galaxy A50 on Android 12, running mihon 0.16.3

**Comment by dgw** [comment]
> 2- edge swiping back to close the app

Wow, thanks for mentioning this. I didn't even think about the fact that my device is using edge-swipe navigation when filing my initial report.

I will have to pay attention to which side of the screen I use for Back gestures. The bulk of my library is in the first category tab, and therefore swipes from the right edge should have a much higher chance of triggering this crash if it is indeed related to the Back gesture also triggering a category change. (_If I can remember to do so,_) I'll go a few days only swiping from the left and see if it affects how often I get this crash.

**Comment by pudup** [comment]
Seems to be the same as #282

**Comment by dgw** [comment]
@pudup So it does, indeed. Don't know how I missed that across 3 or 4 searches of the issue tracker before opening this.
