### ISSUE TITLE
Crash when removing items from library

### ISSUE THREAD

**Issue by THElegend5** [mihonapp/mihon#93]
### Steps to reproduce

1. Open tachiyomi.
2. Open any category.
3. Remove multiple items from this category.

### Expected behavior

Nothing happens.

### Actual behavior

Tachiyomi crashes.

### Crash logs

09-19 02:11:20.146 19324 19492 E CursorWindow: Failed to read row 613, column 0 from a CursorWindow which has 613 rows, 21 columns.
09-19 02:11:20.187 19324 19555 E ACRA    : ACRA caught a NullPointerException for eu.kanade.tachiyomi.debug
09-19 02:11:20.187 19324 19555 E ACRA    : java.lang.NullPointerException
09-19 02:11:20.187 19324 19555 E ACRA    : 	at eu.kanade.tachiyomi.app.CategoriesQueriesImpl$getCategories$1$$ExternalSyntheticOutline0.m(R8$$SyntheticClass:1)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at eu.kanade.tachiyomi.app.MangasQueriesImpl$getLibrary$1.invoke(DatabaseImpl.kt:20)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-19 02:11:20.187 19324 19555 E ACRA    : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
09-19 02:11:20.187 19324 19555 E ACRA    : 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2c9dded, Dispatchers.IO]

### Mihon version

0.16.0

### Android version

Android 14

### Device

Samsung S21 FE

### Other details

https://private-user-images.githubusercontent.com/63903377/189610647-81e213fb-debd-412c-a62b-e5feab33b89f.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTkyMDksIm5iZiI6MTcwNTUxODkwOSwicGF0aCI6Ii82MzkwMzM3Ny8xODk2MTA2NDctODFlMjEzZmItZGViZC00MTJjLWE2MmItZTVmZWFiMzNiODlmLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE5MTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YWY5OWIyMTgyYTZkZWY5OGMzY2MyYzkyN2E5YzNlNzg1MDhhMzdhYjU1ODgxNzJjMWRiYTZiMDIyZjVkNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.py8kV9h53gz-iRn6CR0PCW2lTEeD9a0faa7TyPzj50I

The crash still happens in mihon.

~Reference: https://github.com/tachiyomiorg/tachiyomi/issues/7997~
Reference: http://web.archive.org/web/20240130145643/https://git.mihon.dev/tachiyomi/tachiyomi/issues/7997

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment]
this bug already here is tachiyomi. hope it can be fixed

**Comment by trancephormer** [comment]
Happening with me as well 

https://github.com/user-attachments/assets/b344bd02-f385-4704-8ecf-9013dbe00fd0

[mihon_crash_logs.txt](https://github.com/user-attachments/files/16356030/mihon_crash_logs.txt)

**Comment by humdogm** [comment]
Hi, I have investigated this issue
Look like when you call `MangaScreenModel.kt: toggleFavorite()`, which eventually makes a database update in the generated flie `MangasQueries.kt`, if `LibraryScreenModel.kt` is in the process of collecting the flow `getLibraryFlow()` and is iterating over the cursor in `libraryViewQueries.library()`, I think the cursor may start out thinking that there are a certain number of rows returned by the SQL SELECT query, but that reduces by 1 when you remove a manga from favorites.

That I think tracks with the error in the log saying "CursorWindow: Failed to read row 613, column 0 from a CursorWindow which has 613 rows, 21 columns." So the CursorWindow may be changing while being read?

**Comment by MajorTanya** [comment]
> Hi, I have investigated this issue Look like when you call `MangaScreenModel.kt: toggleFavorite()`, which eventually makes a database update in the generated flie `MangasQueries.kt`, if `LibraryScreenModel.kt` is in the process of collecting the flow `getLibraryFlow()` and is iterating over the cursor in `libraryViewQueries.library()`, I think the cursor may start out thinking that there are a certain number of rows returned by the SQL SELECT query, but that reduces by 1 when you remove a manga from favorites.
> 
> That I think tracks with the error in the log saying "CursorWindow: Failed to read row 613, column 0 from a CursorWindow which has 613 rows, 21 columns." So the CursorWindow may be changing while being read?

Are you experiencing this same crash in newer Mihon versions too?

**Comment by humdogm** [comment]
Yes, I am playing with this in android studio and I am seeing the same crash in 0.17.1

Tbh I have seen this issue since it was Tachiyomi, I just decided I wanted to see what was going on a few days ago

**Comment by humdogm** [comment]
Seems like you need a large number of manga in your database to see this issue

**Comment by humdogm** [comment]
I tried adding some transaction stuff in `MangaRepository.kt` in `getLibraryMangaAsFlow()` but that didn't seem to help, not sure why. PR Incoming to just handle the exception instead.

**Comment by MajorTanya** [comment]
>in android studio
This is the first time I think I've heard someone get this on an emulator, nice work. Is this reproducible reliably or is it still a bit flaky in the emulator?
> Seems like you need a large number of manga in your database to see this issue
What sort of sizes are we talking here? Personally, I have about 1,400 titles and cannot recall ever seeing this.
Do you use a backup to add all those titles or did you add a lot of titles directly in the emulator?

(also, editing messages helps to reduce email notifications people might get 😉)
